# Generated by Django 3.2 on 2025-07-02 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_workouttemplate_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='workout',
            name='templates',
            field=models.ManyToManyField(blank=True, to='app.WorkoutTemplate'),
        ),
    ]
