# Generated by Django 3.2 on 2025-07-02 16:33

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_workout_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='workout',
            name='workout_id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
