# Generated by Django 3.2 on 2025-07-21 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workouts', '0003_auto_20250708_2202'),
    ]

    operations = [
        migrations.AddField(
            model_name='set',
            name='rpe',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
