# Generated by Django 3.2 on 2025-07-01 09:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20250701_0949'),
    ]

    operations = [
        migrations.RenameField(
            model_name='exercise',
            old_name='type',
            new_name='muscle_group',
        ),
    ]
